version: '3.7'

services:
  mysql:
    image: "mysql:latest"
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_USER: "root"
#      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "bookstore_db"
    ports:
      - "3306:3306"
    restart: always